### ISSUE TITLE
Support Evolve

### ISSUE THREAD

**Issue by hdpoliveira** [mrcrowl/vscode-hg#114]

**Comment by mrcrowl** [comment]
Just adding my 2c here. 

I would argue that the purpose of the vscode-hg extension is to provide the _core_ features of mercurial as a convenience, rather than to be a fully-fledged mercurial GUI. 

The evolve extraction, [as it is described](https://www.mercurial-scm.org/wiki/EvolveExtension) is experimental. To my thinking, the commands it provides should be rarely needed and could be run from the command line.

**Comment by hdpoliveira** [comment]
Yeah I think you're right...

**Comment by hdpoliveira** [comment]
The point of having support to evolve is that users who use it depend a lot on it, to the point that they consider it as core (I am one of those :smile: )

I'll try to observe how often I need to use evolve commands/features and reflect on this a bit.

I agree that we should try to be a fully-fledged mercurial GUI.

**Comment by mrcrowl** [comment]
One option that you might consider is to make vcode-hg itself extensible, and then write a separate extension for the advanced Mercurial usage. 

VS Code provides a way to access the API of another extension. See the [relevant docs here](https://code.visualstudio.com/api/references/vscode-api#extensions).

**Comment by hdpoliveira** [comment]
Nice!

**Comment by incidentist** [comment]
Yeah, that's what the git extension does and the api it exposes is used by extensions like GitLens. I would like to do this to make something like GitGraph for hg, that would use the api exported by this extension.

**Comment by hdpoliveira** [comment]
I'll close this issue then! Thanks for your inputs!
