### ISSUE TITLE
Support File History UI

### ISSUE THREAD

**Issue by hdpoliveira** [mrcrowl/vscode-hg#118]
Something similar to what GitLens does: https://www.youtube.com/watch?v=bRdQw4-sGIY

We already have a File History command, so this issue is about supporting a GUI

**Comment by incidentist** [comment]
How do you feel about the GUI for this being the Timeline view (#77) instead of being driven by the command palette?

**Comment by hdpoliveira** [comment]
I think you are right but I'm not sure.
The only way to know is implementing #77 and checking if it is enough.
Are you working on #77?

**Comment by mrcrowl** [comment]
Makes sense to me to use timeline. Command palette always felt like a hack.

**Comment by hdpoliveira** [comment]
Closing in favor of #77

**Comment by incidentist** [comment]
> Are you working on #77?

I started on it awhile back, but moved on to other stuff because it's not clear to me if we can ship an extension that uses the Timeline API since it isn't finalized yet. If you want to take it, go for it. I did maybe 20 minutes of work that probably isn't worth reviving since the repo has changed so much.
